locals {
  name_prefix = "${var.project_name}-${var.environment}"
  common_tags = merge(var.tags, {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
    Module      = "rds"
  })
}

# Random password generated by Terraform rather than typed into a .tfvars
# file — avoids the credential ever existing in plaintext in version control
# or in a human's clipboard. It's written straight into Secrets Manager below.
resource "random_password" "db_master" {
  length           = 24
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "random_pet" "secret_suffix" {
  length    = 2
  separator = "-"
}

resource "aws_secretsmanager_secret" "db_credentials" {
  name                    = "${local.name_prefix}-rds-credential-${random_pet.secret_suffix.id}"
  description             = "Master credentials for the ${local.name_prefix} RDS MySQL instance."
  recovery_window_in_days = 0

  tags = local.common_tags
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_master.result
    engine   = "mysql"
    dbname   = var.db_name
  })
}

resource "aws_db_parameter_group" "mysql" {
  name   = "${local.name_prefix}-mysql-params"
  family = "mysql8.0"

  # Explicit UTF-8 (4-byte) charset so emoji / non-Latin content in daily
  # reports and comments (French, Arabic users targeted by the EU/NA expansion)
  # store correctly instead of silently truncating.
  parameter {
    name  = "character_set_server"
    value = "utf8mb4"
  }

  parameter {
    name  = "collation_server"
    value = "utf8mb4_unicode_ci"
  }

  tags = local.common_tags
}

resource "aws_db_instance" "this" {
  identifier = "${local.name_prefix}-rds"

  engine         = "mysql"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = "gp2"
  storage_encrypted     = true
  kms_key_id            = var.kms_key_id

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db_master.result

  db_subnet_group_name   = var.db_subnet_group_name
  vpc_security_group_ids = var.vpc_security_group_ids
  parameter_group_name   = aws_db_parameter_group.mysql.name

  multi_az = var.multi_az

  backup_retention_period = var.backup_retention_period
  backup_window           = var.backup_window
  maintenance_window      = var.maintenance_window
  copy_tags_to_snapshot   = true

  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${local.name_prefix}-final-snapshot"

  # Not publicly accessible under any circumstance — the network layer
  # already blocks internet routes for this subnet, this is a second,
  # independent control ("defense in depth").
  publicly_accessible = false

  enabled_cloudwatch_logs_exports = ["error", "slowquery"]

  tags = merge(local.common_tags, { Name = "${local.name_prefix}-rds" })
}
